apiVersion: v1
kind: Secret
metadata:
  name: cloudtask-secret
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: pass
  POSTGRES_DB: cloudtask
  SECRET_KEY: troque-esta-chave-secreta
  DATABASE_URL: postgresql://user:pass@db:5432/cloudtask
